Add functions for batch method
NightWriter/go-bitrix pull request #23
Opened 2022-07-05 13:51 UTC by GoopaloUA

2022-07-13 16:11 UTC, NightWriter requested changes

2022-07-13 16:11 UTC, NightWriter commented on client/client.go
> +var (
this should be const

2022-07-13 18:15 UTC, GoopaloUA reviewed
BatchLimit and ResponseOffset is const now

2022-07-13 18:16 UTC, GoopaloUA commented on client/client.go
> +var (
Done

2022-07-14 09:25 UTC, NightWriter approved these changes

2022-07-14 09:25 UTC, merged